MODULE ZUPKZ;

REQUIRE KZOrganization, KZLegalFramework, HRDepartment, HRPosition,
        HREmployee, HRStaffSchedule, HREmployment;
NAMESPACE ZUPKZ;

NAVIGATOR {
    NEW FOLDER masterData 'Справочники' WINDOW toolbar {
        NEW organizations;
        NEW departments;
        NEW positions;
        NEW employees;
        NEW staffPositions;
    }

    NEW FOLDER legislation 'Законодательство РК' WINDOW toolbar {
        NEW legalSources;
        NEW statutoryParameters;
        NEW statutoryParameterValues;
    }

    NEW FOLDER personnel 'Кадровый учёт' WINDOW toolbar {
        NEW employments;
        NEW employmentAssignments;
        NEW personnelEvents;
    }
}
