MODULE HREmployee;

REQUIRE Utils;
NAMESPACE ZUPKZ;

CLASS Employee 'Сотрудник';

CLASS Gender 'Пол' {
    male 'Мужской',
    female 'Женский'
}

iin 'ИИН' = DATA STRING[12] (Employee);
lastName 'Фамилия' = DATA STRING[100] (Employee);
firstName 'Имя' = DATA STRING[100] (Employee);
middleName 'Отчество' = DATA STRING[100] (Employee);
birthDate 'Дата рождения' = DATA DATE (Employee);
gender 'Пол' = DATA Gender (Employee);
citizenshipCode 'Код страны гражданства' = DATA STRING[3] (Employee);
personalDataConsentDate 'Дата согласия на обработку ПД' = DATA DATE (Employee);
personalDataPurpose 'Цель обработки ПД' = DATA STRING[250] (Employee);

employeeFullName 'Ф.И.О.' (Employee e) =
    lastName(e) + ' ' + firstName(e) +
    (IF middleName(e) THEN ' ' + middleName(e) ELSE '');

employeeIinCount(STRING[12] value) = GROUP SUM 1 IF iin(Employee e) == value;
CONSTRAINT iin(Employee e) AND length(iin(e)) != 12
    MESSAGE 'ИИН должен содержать 12 символов';
CONSTRAINT iin(Employee e) AND NOT onlyDigits(iin(e))
    MESSAGE 'ИИН должен состоять только из цифр';
CONSTRAINT employeeIinCount(STRING[12] value) > 1
    MESSAGE 'ИИН должен быть уникальным';

FORM employees 'Сотрудники'
    OBJECTS e = Employee
    PROPERTIES(e) READONLY employeeFullName
    PROPERTIES(e) iin, lastName, firstName, middleName, birthDate, gender,
                  citizenshipCode, personalDataConsentDate, personalDataPurpose
;
